###register request
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username" : "hamzeh",
    "email" : "asakereh.hamzeh@gmail.com",
    "mobile" : "09123456789",
    "password" : "123456",
    "confirm_password" : "123456"
}